### ISSUE TITLE
"Could not find fasta file"

### ISSUE THREAD

**Issue by blsteven** [snz20/carnelian#3]
When I try and run the training command
carnelian train -k 8 --num_hash 2 -l 30 -c 5 data/EC-2010-DB model_dir

I get the following error:
Namespace(bits=31, coverage=5.0, frag_length=30, hweight=-1, kmer_length=8, lambda1=0.0, lambda2=0.0, mode='train', model_dir='model_dir', num_batches=1, num_hash=2, num_passes=1, precise=False, rweight=4, train_dir='data/EC-2010-DB')
Traceback (most recent call last):
  File "/usr/local/src/carnelian/carnelian", line 1345, in <module>
    main(sys.argv[1:])
  File "/usr/local/src/carnelian/carnelian", line 1327, in main
    train(args.train_dir, args.model_dir, args)
  File "/usr/local/src/carnelian/carnelian", line 575, in train
    fasta, labels = get_fasta_and_label(ref_dir)
  File "/usr/local/src/carnelian/carnelian", line 126, in get_fasta_and_label
    raise RuntimeError("Could not find fasta file in:" + directory)

I checked the directory and there is a seq.fasta file there.

Both tests ran successfully.

Ant help is much appreciated

Thanks!

**Comment by snz20** [comment]
Hi, I could not reproduce your error. I ran it on my local machine, seems to work perfectly fine. 
[Unrelated to this problem] while training, you should add some negative examples in your fasta file and update the label file accordingly.
