### ISSUE TITLE
"sampleinfo_file" format and creation

### ISSUE THREAD

**Issue by BeckyGenomics** [snz20/carnelian#4]
Hi there,

I'm trying to follow the instructions in part C of the workflow (Functional profiling and abundance analysis). I have copied the .label files of my two samples to a labels_dir/. I am confused about the sample info_file file, I presume that is something I have to create? 

In the workflow it states:

The files should be named after the same sample identifiers that appear in the sampleinfo_file file. See the readme.txt file for the format of sampleinfo_file.
Run the following command for creating the raw and effective counts matrices: 
carnelian abundance labels_dir abundance_matrix_dir sampleinfo_file data/EC-2010-DB/ec_lengths.tsv

I have checked the readme.txt and I cannot find instructions for creating the sample info_file. I would really appreciate any advice or help with this, as I am a student with quite a short deadline. 

Thank you in advance for your help,
Becky

**Comment by snz20** [comment]
Hi Becky, 

The sampleinfo_file is a tab-separated file with three columns: sample_id, group, fraglen. sample_id column will contain the unique sample identifiers, group will indicate the classes the samples belong to. For example, if it is a case-control study, this column will contain case/control, or if it is a population study, it could contain the ancestry of the samples. The fraglen column will contain the average read length of sequences in amino acids for each sample (say your sequences have an average length of 120 bp, then the entry for it will be 40). You can see an example of the sampleinfo_file under the tests/demo_data folder: https://github.com/snz20/carnelian/blob/master/tests/demo_data/map.tab

Best,
Sumaiya

**Comment by BeckyGenomics** [comment]
Hi Sumaiya, 

Just wanted to thank you for taking the time to respond to me, I really appreciate your help.

Best wishes,
Becky
