### ISSUE TITLE
TabError in carnelian.py

### ISSUE THREAD

**Issue by fischer-hub** [snz20/carnelian#5]
Nice Project! Sadly on start I get a TabError:
```
probfile = os.path.join(os.path.dirname(outputfile),'label-probabilities.tsv')
TabError: inconsistent use of tabs and spaces in indentation
```
This happens after cloning and running the `SETUP.sh`.
I looked into the `carnelian.py` and I found lots of shifted indentations after running `SETUP.sh`.. I was able to fix the indentation by running: 
```
autopep8 -i carnelian.py
```
but still really weird behaviour!
Happy holidays!

**Comment by snz20** [comment]
Thanks for pointing it out.
